COMMENT ON TABLE sys_user IS '系统用户表，存储登录账号、展示名称、身份类型与启停状态';
COMMENT ON COLUMN sys_user.id IS '用户主键 ID';
COMMENT ON COLUMN sys_user.username IS '登录用户名，系统内唯一';
COMMENT ON COLUMN sys_user.display_name IS '用户展示名称，用于界面显示';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希值，不存储明文密码';
COMMENT ON COLUMN sys_user.user_type IS '用户类型，例如管理员或普通用户';
COMMENT ON COLUMN sys_user.status IS '用户状态，例如启用或禁用';
COMMENT ON COLUMN sys_user.created_at IS '记录创建时间';
COMMENT ON COLUMN sys_user.updated_at IS '记录最后更新时间';
COMMENT ON COLUMN sys_user.deleted IS '逻辑删除标记，0 表示未删除，1 表示已删除';

COMMENT ON TABLE workspace IS '工作空间表，存储代码仓库、分支与运行目标等上下文信息';
COMMENT ON COLUMN workspace.id IS '工作空间主键 ID';
COMMENT ON COLUMN workspace.name IS '工作空间名称';
COMMENT ON COLUMN workspace.repository_url IS '关联代码仓库地址';
COMMENT ON COLUMN workspace.branch_name IS '工作空间对应的代码分支名称';
COMMENT ON COLUMN workspace.working_directory IS '本地工作目录路径';
COMMENT ON COLUMN workspace.runtime_target IS '运行目标类型，例如 Web、MCP 或 Electron';
COMMENT ON COLUMN workspace.created_by IS '创建人用户 ID';
COMMENT ON COLUMN workspace.created_at IS '记录创建时间';
COMMENT ON COLUMN workspace.updated_at IS '记录最后更新时间';
COMMENT ON COLUMN workspace.deleted IS '逻辑删除标记，0 表示未删除，1 表示已删除';

COMMENT ON TABLE task IS '任务表，存储任务标题、执行状态、运行类型与结果摘要';
COMMENT ON COLUMN task.id IS '任务主键 ID';
COMMENT ON COLUMN task.title IS '任务标题';
COMMENT ON COLUMN task.description IS '任务详细描述';
COMMENT ON COLUMN task.status IS '任务当前状态';
COMMENT ON COLUMN task.runtime_type IS '任务运行时类型';
COMMENT ON COLUMN task.workspace_id IS '关联工作空间 ID';
COMMENT ON COLUMN task.created_by IS '任务创建人用户 ID';
COMMENT ON COLUMN task.started_at IS '任务开始执行时间';
COMMENT ON COLUMN task.finished_at IS '任务执行完成时间';
COMMENT ON COLUMN task.error_message IS '任务失败时的错误信息';
COMMENT ON COLUMN task.summary IS '任务执行结果摘要';
COMMENT ON COLUMN task.created_at IS '记录创建时间';
COMMENT ON COLUMN task.updated_at IS '记录最后更新时间';
COMMENT ON COLUMN task.deleted IS '逻辑删除标记，0 表示未删除，1 表示已删除';

COMMENT ON TABLE task_event IS '任务事件表，按顺序记录任务执行过程中的阶段事件与附加元数据';
COMMENT ON COLUMN task_event.id IS '任务事件主键 ID';
COMMENT ON COLUMN task_event.task_id IS '所属任务 ID';
COMMENT ON COLUMN task_event.event_type IS '事件类型';
COMMENT ON COLUMN task_event.sequence_no IS '事件顺序号，用于保持时间线顺序';
COMMENT ON COLUMN task_event.title IS '事件标题';
COMMENT ON COLUMN task_event.content IS '事件详细内容';
COMMENT ON COLUMN task_event.metadata_json IS '事件附加元数据 JSON 文本';
COMMENT ON COLUMN task_event.created_at IS '事件创建时间';

COMMENT ON TABLE task_artifact IS '任务产物表，存储任务生成的文档、内容或文件路径';
COMMENT ON COLUMN task_artifact.id IS '任务产物主键 ID';
COMMENT ON COLUMN task_artifact.task_id IS '所属任务 ID';
COMMENT ON COLUMN task_artifact.artifact_type IS '产物类型';
COMMENT ON COLUMN task_artifact.name IS '产物名称';
COMMENT ON COLUMN task_artifact.content IS '产物文本内容';
COMMENT ON COLUMN task_artifact.storage_path IS '产物文件存储路径';
COMMENT ON COLUMN task_artifact.created_at IS '产物创建时间';

COMMENT ON TABLE chat_conversation IS '会话表，存储用户与助手的对话主题、状态和最近活跃时间';
COMMENT ON COLUMN chat_conversation.id IS '会话主键 ID';
COMMENT ON COLUMN chat_conversation.title IS '会话标题';
COMMENT ON COLUMN chat_conversation.created_by IS '会话创建人用户 ID';
COMMENT ON COLUMN chat_conversation.status IS '会话状态';
COMMENT ON COLUMN chat_conversation.last_message_at IS '最近一条消息产生时间';
COMMENT ON COLUMN chat_conversation.created_at IS '记录创建时间';
COMMENT ON COLUMN chat_conversation.updated_at IS '记录最后更新时间';
COMMENT ON COLUMN chat_conversation.deleted IS '逻辑删除标记，0 表示未删除，1 表示已删除';

COMMENT ON TABLE chat_message IS '会话消息表，存储对话中的角色消息、模型信息与发送状态';
COMMENT ON COLUMN chat_message.id IS '消息主键 ID';
COMMENT ON COLUMN chat_message.conversation_id IS '所属会话 ID';
COMMENT ON COLUMN chat_message.role IS '消息角色，例如用户或助手';
COMMENT ON COLUMN chat_message.content IS '消息内容';
COMMENT ON COLUMN chat_message.status IS '消息处理状态';
COMMENT ON COLUMN chat_message.provider IS '消息对应的模型服务提供方';
COMMENT ON COLUMN chat_message.model IS '消息对应的模型名称';
COMMENT ON COLUMN chat_message.error_message IS '消息处理失败时的错误信息';
COMMENT ON COLUMN chat_message.created_at IS '记录创建时间';
COMMENT ON COLUMN chat_message.updated_at IS '记录最后更新时间';
