-- 为系统配置表补齐 AI endpoint 与候选池键位，使 app.ai 可完全由数据库配置控制。
INSERT INTO setting (
    id,
    setting_key,
    setting_value,
    encrypted_value,
    secret,
    masked_value,
    encryption_algorithm,
    encryption_key_version,
    value_type,
    category_code,
    description,
    sort_no,
    restart_required,
    deleted
)
VALUES
    (7201, 'ai.providers.siliconflow.endpoints.chat', '/v1/chat/completions', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.providers', '硅基流动聊天端点路径', 190, FALSE, 0),
    (7202, 'ai.providers.bailian.endpoints.chat', '/compatible-mode/v1/chat/completions', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.providers', '百炼聊天端点路径', 200, FALSE, 0),
    (7203, 'ai.providers.deepseek.endpoints.chat', '/chat/completions', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.providers', 'DeepSeek 聊天端点路径', 210, FALSE, 0),
    (7210, 'ai.chat.candidates.10.id', 'siliconflow-deepseek-v4-flash', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 10 模型ID', 10, FALSE, 0),
    (7211, 'ai.chat.candidates.10.provider', 'siliconflow', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 10 提供商', 20, FALSE, 0),
    (7212, 'ai.chat.candidates.10.model', 'deepseek-ai/DeepSeek-V4-Flash', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 10 模型名称', 30, FALSE, 0),
    (7213, 'ai.chat.candidates.10.priority', '1', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 10 优先级', 40, FALSE, 0),
    (7214, 'ai.chat.candidates.10.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 10 是否启用', 50, FALSE, 0),
    (7215, 'ai.chat.candidates.10.supports_thinking', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 10 是否支持思考模式', 60, FALSE, 0),
    (7216, 'ai.chat.candidates.10.supports_vision', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 10 是否支持视觉', 70, FALSE, 0),
    (7220, 'ai.chat.candidates.20.id', 'siliconflow-deepseek-v4-flash-thinking', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 20 模型ID', 80, FALSE, 0),
    (7221, 'ai.chat.candidates.20.provider', 'siliconflow', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 20 提供商', 90, FALSE, 0),
    (7222, 'ai.chat.candidates.20.model', 'deepseek-ai/DeepSeek-V4-Flash', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 20 模型名称', 100, FALSE, 0),
    (7223, 'ai.chat.candidates.20.priority', '2', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 20 优先级', 110, FALSE, 0),
    (7224, 'ai.chat.candidates.20.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 20 是否启用', 120, FALSE, 0),
    (7225, 'ai.chat.candidates.20.supports_thinking', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 20 是否支持思考模式', 130, FALSE, 0),
    (7226, 'ai.chat.candidates.20.supports_vision', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 20 是否支持视觉', 140, FALSE, 0),
    (7230, 'ai.chat.candidates.30.id', 'siliconflow-qwen3.5-122b-a10b', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 30 模型ID', 150, FALSE, 0),
    (7231, 'ai.chat.candidates.30.provider', 'siliconflow', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 30 提供商', 160, FALSE, 0),
    (7232, 'ai.chat.candidates.30.model', 'Qwen/Qwen3.5-122B-A10B', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 30 模型名称', 170, FALSE, 0),
    (7233, 'ai.chat.candidates.30.priority', '3', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 30 优先级', 180, FALSE, 0),
    (7234, 'ai.chat.candidates.30.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 30 是否启用', 190, FALSE, 0),
    (7235, 'ai.chat.candidates.30.supports_thinking', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 30 是否支持思考模式', 200, FALSE, 0),
    (7236, 'ai.chat.candidates.30.supports_vision', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 30 是否支持视觉', 210, FALSE, 0),
    (7240, 'ai.chat.candidates.40.id', 'qwen-plus', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 40 模型ID', 220, FALSE, 0),
    (7241, 'ai.chat.candidates.40.provider', 'bailian', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 40 提供商', 230, FALSE, 0),
    (7242, 'ai.chat.candidates.40.model', 'qwen-plus-latest', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 40 模型名称', 240, FALSE, 0),
    (7243, 'ai.chat.candidates.40.priority', '4', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 40 优先级', 250, FALSE, 0),
    (7244, 'ai.chat.candidates.40.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 40 是否启用', 260, FALSE, 0),
    (7245, 'ai.chat.candidates.40.supports_thinking', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 40 是否支持思考模式', 270, FALSE, 0),
    (7246, 'ai.chat.candidates.40.supports_vision', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 40 是否支持视觉', 280, FALSE, 0),
    (7250, 'ai.chat.candidates.50.id', 'qwen3-max', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 50 模型ID', 290, FALSE, 0),
    (7251, 'ai.chat.candidates.50.provider', 'bailian', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 50 提供商', 300, FALSE, 0),
    (7252, 'ai.chat.candidates.50.model', 'qwen3-max', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 50 模型名称', 310, FALSE, 0),
    (7253, 'ai.chat.candidates.50.priority', '5', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 50 优先级', 320, FALSE, 0),
    (7254, 'ai.chat.candidates.50.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 50 是否启用', 330, FALSE, 0),
    (7255, 'ai.chat.candidates.50.supports_thinking', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 50 是否支持思考模式', 340, FALSE, 0),
    (7256, 'ai.chat.candidates.50.supports_vision', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 50 是否支持视觉', 350, FALSE, 0),
    (7260, 'ai.chat.candidates.60.id', 'qwen3.6-plus', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 60 模型ID', 360, FALSE, 0),
    (7261, 'ai.chat.candidates.60.provider', 'bailian', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 60 提供商', 370, FALSE, 0),
    (7262, 'ai.chat.candidates.60.model', 'qwen3.6-plus', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 60 模型名称', 380, FALSE, 0),
    (7263, 'ai.chat.candidates.60.priority', '6', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 60 优先级', 390, FALSE, 0),
    (7264, 'ai.chat.candidates.60.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 60 是否启用', 400, FALSE, 0),
    (7265, 'ai.chat.candidates.60.supports_thinking', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 60 是否支持思考模式', 410, FALSE, 0),
    (7266, 'ai.chat.candidates.60.supports_vision', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 60 是否支持视觉', 420, FALSE, 0),
    (7270, 'ai.chat.candidates.70.id', 'glm-4.7', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 70 模型ID', 430, FALSE, 0),
    (7271, 'ai.chat.candidates.70.provider', 'siliconflow', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 70 提供商', 440, FALSE, 0),
    (7272, 'ai.chat.candidates.70.model', 'Pro/zai-org/GLM-4.7', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 70 模型名称', 450, FALSE, 0),
    (7273, 'ai.chat.candidates.70.priority', '7', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 70 优先级', 460, FALSE, 0),
    (7274, 'ai.chat.candidates.70.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 70 是否启用', 470, FALSE, 0),
    (7275, 'ai.chat.candidates.70.supports_thinking', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 70 是否支持思考模式', 480, FALSE, 0),
    (7276, 'ai.chat.candidates.70.supports_vision', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 70 是否支持视觉', 490, FALSE, 0),
    (7280, 'ai.chat.candidates.80.id', 'deepseek-v4-flash', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 80 模型ID', 500, FALSE, 0),
    (7281, 'ai.chat.candidates.80.provider', 'deepseek', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 80 提供商', 510, FALSE, 0),
    (7282, 'ai.chat.candidates.80.model', 'deepseek-v4-flash', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 80 模型名称', 520, FALSE, 0),
    (7283, 'ai.chat.candidates.80.priority', '8', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 80 优先级', 530, FALSE, 0),
    (7284, 'ai.chat.candidates.80.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 80 是否启用', 540, FALSE, 0),
    (7285, 'ai.chat.candidates.80.supports_thinking', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 80 是否支持思考模式', 550, FALSE, 0),
    (7286, 'ai.chat.candidates.80.supports_vision', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 80 是否支持视觉', 560, FALSE, 0),
    (7290, 'ai.chat.candidates.90.id', 'deepseek-reasoner', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 90 模型ID', 570, FALSE, 0),
    (7291, 'ai.chat.candidates.90.provider', 'deepseek', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 90 提供商', 580, FALSE, 0),
    (7292, 'ai.chat.candidates.90.model', 'deepseek-reasoner', NULL, FALSE, NULL, NULL, NULL, 'STRING', 'ai.candidates', '候选 90 模型名称', 590, FALSE, 0),
    (7293, 'ai.chat.candidates.90.priority', '9', NULL, FALSE, NULL, NULL, NULL, 'INTEGER', 'ai.candidates', '候选 90 优先级', 600, FALSE, 0),
    (7294, 'ai.chat.candidates.90.enabled', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 90 是否启用', 610, FALSE, 0),
    (7295, 'ai.chat.candidates.90.supports_thinking', 'true', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 90 是否支持思考模式', 620, FALSE, 0),
    (7296, 'ai.chat.candidates.90.supports_vision', 'false', NULL, FALSE, NULL, NULL, NULL, 'BOOLEAN', 'ai.candidates', '候选 90 是否支持视觉', 630, FALSE, 0)
ON CONFLICT (setting_key) DO UPDATE
SET setting_value = EXCLUDED.setting_value,
    value_type = EXCLUDED.value_type,
    category_code = EXCLUDED.category_code,
    description = EXCLUDED.description,
    sort_no = EXCLUDED.sort_no,
    restart_required = EXCLUDED.restart_required,
    updated_at = CURRENT_TIMESTAMP,
    deleted = EXCLUDED.deleted;
