INSERT INTO chat_tool (id, tool_code, display_name, description, category, source_type, enabled, sort_no, deleted)
VALUES
    (9101, 'shell_command', 'Shell 命令执行', '在当前工作区执行终端命令', '终端', 'codex-cli', 1, 1, 0),
    (9102, 'apply_patch', '补丁编辑', '通过补丁语法修改本地文件', '代码编辑', 'codex-cli', 1, 2, 0),
    (9103, 'list_mcp_resources', '列出 MCP 资源', '读取已接入 MCP 服务的资源列表', 'MCP', 'codex-cli', 1, 3, 0),
    (9104, 'list_mcp_resource_templates', '列出 MCP 资源模板', '读取已接入 MCP 服务的参数化资源模板', 'MCP', 'codex-cli', 1, 4, 0),
    (9105, 'read_mcp_resource', '读取 MCP 资源', '按资源 URI 读取 MCP 资源内容', 'MCP', 'codex-cli', 1, 5, 0),
    (9106, 'update_plan', '更新执行计划', '维护任务步骤与状态', '规划', 'codex-cli', 1, 6, 0),
    (9107, 'request_user_input', '请求用户输入', '发起结构化问题并等待用户选择', '交互', 'codex-cli', 1, 7, 0),
    (9108, 'view_image', '查看本地图片', '读取并分析本地图片文件', '多模态', 'codex-cli', 1, 8, 0),
    (9109, 'spawn_agent', '创建子代理', '启动子代理执行并行任务', '多代理', 'codex-cli', 1, 9, 0),
    (9110, 'send_input', '发送消息给子代理', '向已有子代理发送新指令', '多代理', 'codex-cli', 1, 10, 0),
    (9111, 'wait_agent', '等待子代理完成', '等待子代理返回最终结果', '多代理', 'codex-cli', 1, 11, 0),
    (9112, 'close_agent', '关闭子代理', '结束子代理及其上下文', '多代理', 'codex-cli', 1, 12, 0),
    (9113, 'resume_agent', '恢复子代理', '恢复已关闭子代理并继续对话', '多代理', 'codex-cli', 1, 13, 0),
    (9114, 'tool_search', '工具搜索', '在可安装工具中按语义搜索候选项', '扩展', 'codex-cli', 1, 14, 0),
    (9115, 'request_plugin_install', '请求安装插件', '建议用户安装缺失的插件或连接器', '扩展', 'codex-cli', 1, 15, 0),
    (9116, 'request_permissions', '请求权限提升', '在受限环境中申请命令权限', '权限', 'codex-cli', 1, 16, 0),
    (9117, 'exec_command', '统一执行命令', '在统一执行后端中运行命令', '终端', 'codex-cli', 1, 17, 0),
    (9118, 'write_stdin', '写入标准输入', '向运行中的命令进程写入标准输入', '终端', 'codex-cli', 1, 18, 0),
    (9119, 'get_goal', '读取目标', '获取当前会话目标定义', '目标', 'codex-cli', 1, 19, 0),
    (9120, 'create_goal', '创建目标', '创建新的目标定义', '目标', 'codex-cli', 1, 20, 0),
    (9121, 'update_goal', '更新目标', '更新已有目标定义', '目标', 'codex-cli', 1, 21, 0),
    (9122, 'send_message', '发送消息', '向多代理 V2 线程发送消息', '多代理', 'codex-cli', 1, 22, 0),
    (9123, 'followup_task', '追加任务', '向多代理 V2 追加后续任务', '多代理', 'codex-cli', 1, 23, 0),
    (9124, 'list_agents', '列出子代理', '列出当前会话中的子代理', '多代理', 'codex-cli', 1, 24, 0),
    (9125, 'spawn_agents_on_csv', 'CSV 批量生成子代理', '根据 CSV 批量创建子代理任务', '批处理', 'codex-cli', 1, 25, 0),
    (9126, 'report_agent_job_result', '上报子代理任务结果', '上报批量子代理任务的执行结果', '批处理', 'codex-cli', 1, 26, 0),
    (9127, 'test_sync_tool', '同步测试工具', '用于工具链路调试与连通性验证', '调试', 'codex-cli', 1, 27, 0)
ON CONFLICT (tool_code) DO UPDATE
SET
    display_name = EXCLUDED.display_name,
    description = EXCLUDED.description,
    category = EXCLUDED.category,
    source_type = EXCLUDED.source_type,
    enabled = EXCLUDED.enabled,
    sort_no = EXCLUDED.sort_no,
    updated_at = CURRENT_TIMESTAMP,
    deleted = EXCLUDED.deleted;